### ISSUE TITLE
Handle malformed feeds

### ISSUE THREAD

**Issue by avivace** [avivace/RSSnotifier#9]
A malformed, interrupted or bad-formatted feed usually crashes the feed parser

**Comment by dennib** [comment]
Addressing this in [16bc4c1 ](https://github.com/avivace/RSSnotifier/commit/08b55c71f1c050d2f2394ce1fd587bbeadfa02b1):

**FeedParseDone** was called with an error on every parse-related error occured during feed parsing process and inside of it we were forcing the bot to crash with

```
function feedParseDone(err, rows) {
    log(rows, 1)
    if (err) {
        log(err, err.stack, 0);
        return process.exit(1);
    }
}
```

With last changes we're now avoiding the crash simply logging "an error message" 
in correspondence of the problematic feed (_Full error stack available with logging level 1_).

```
function feedParseDone(err, rows) {
    log(rows, 1)
    if (err) {
        log('Error on feed...', 0);
        log(err, err.stack, 1);
    }
}
```

A "**cooldown**" system for problematic feeds is surely still required but at least the bot can continue to work properly checking the other ones.

I've been testing this for some days now, seems to run flawlessly :P
